language: java
sudo: false
jdk: 
  - openjdk8
script: 
  - mvn clean test
cache:
  directories:
  - $HOME/.m2
deploy:
  provider: lambda
  function_name: "LambdaPOC"
  region: "us-east-1"
  role: "arn:aws:lambda:us-east-2:052686530403:function:LambdaPOC"
  runtime: "java-1.8.0-openjdk"
  handler_name: "handleRequest"
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET